### ISSUE TITLE
Update Firefox Addons site

### ISSUE THREAD

**Issue by Ziggoto** [fuzeman/GoogleMusicScrobbler#29]
Google Music Scrobbler at Mozilla's website still is in version 0.7.3 which is currently broken. Please update that with version 0.7.5 which works fine.

**Comment by fuzeman** [comment]
I purposely stopped sending updates to https://addons.mozilla.org (since [Dec' 2014](https://github.com/fuzeman/GoogleMusicScrobbler/issues/27#issuecomment-65775420)) due to the huge issues in the addon review process.

**Note:** addon update reviews can take up to 6 weeks now *(https://blog.mozilla.org/addons/2015/04/29/add-ons-update-64/)*

---------------------------------------

I won't be releasing any updates on https://addons.mozilla.org until issues with the review process have been resolved in some way.

**Comment by lidel** [comment]
FYI soon all addons will have to be signed by Mozilla:

- https://blog.mozilla.org/addons/2015/02/10/extension-signing-safer-experience/
- https://blog.mozilla.org/addons/2015/04/15/the-case-for-extension-signing/

Without signature official Firefox builds will not run the addon.

**Comment by fuzeman** [comment]
This:
> Extension files that aren’t hosted on AMO will have to be submitted to AMO for signing. Developers will need to create accounts and a listing for their extension, which will not be public. These files will go through an automated review process and sent back signed if all checks pass. If an add-on doesn’t pass the automated tests, the developer will have the option to request the add-on to be manually checked by our review team.

Sounds like it could still be signed (if the automatic tests pass) without the manual review? will need to look into this..

**Comment by fuzeman** [comment]
**Note:** extension is now signed (with the [v0.8.6.2-beta](https://github.com/fuzeman/GoogleMusicScrobbler/releases/tag/0.8.6.2-beta) release), the latest version will be available via the "Development Channel" on the AMO page now: https://addons.mozilla.org/en-US/firefox/addon/google-music-scrobbler/
